name: Thoughtless
favicon: null
layout_spectrum: 0.9358876845799387
typography_spectrum: 0.5545172058045864
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7197471174877137
  lightness: 0.996904079336673
  saturation: 0.5994327371008694
  rhythmicContrast: 0.5941877716686577
purpose: []
