name: Thoughtless
favicon: null
layout_spectrum: 0.59251
typography_spectrum: 0.57462
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#c5c5c5'
    - '#9d9d9d'
    - '#5f5f5f'
  brandStrength: 0.7197471174877137
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.5941877716686577
purpose: []
